### ISSUE TITLE
Responsive videos in widget

### ISSUE THREAD

**Issue by samikeijonen** [grappler/fluidvids#1]
Let's start conversation in here. Responsive videos works in text widget when using [Text Widget oEbmed](https://wordpress.org/plugins/text-widget-oembed/) Plugin. But should you include these filters in your plugin? I think yes.

```
add_filter( 'widget_text', array( $wp_embed, 'run_shortcode' ), 8 );
add_filter( 'widget_text', array( $wp_embed, 'autoembed'), 8 );
```

**Comment by grappler** [comment]
Sorry for the really delayed response. I don't think I want to add this as the plugin is not a plugin for responsive videos but loading fluidvids.

**Comment by samikeijonen** [comment]
What you mean delayd :)
